//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealthCareWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMedicine
    {
        public int ID { get; set; }
        public string MedicineName { get; set; }
        public string Category { get; set; }
        public Nullable<int> Price { get; set; }
        public string Seller { get; set; }
        public string Descriptions { get; set; }
        public byte[] MedicineImage { get; set; }
    }
}
